#OMNILAYER ASSET
OMNILAYER_ID = 3
OMNIASSET_VALUE_TO_SEND = "1.0"

#FUNDING TX CHANGES WHEN AN INPUT OF THE MULTISIG IS SPENT AND CHANGES
FUNDING_TX = ''
FUNDING_VOUT = 0
FUNDING_VALUE = 0.00000001
#THIS KEY IS ASSOCIATED WITH THE FUNDING TX
SCRIPT_PUB_KEY = ''

#FROM, THIS WILL BE THE MULTISIG ADDRESS AS ANY CHANGE WILL RETURN BACK TO IT UNLESS SPECIFIED OTHERWISE
FROM_ADDRESS = ''

#TO, WHERE YOU WANT TO SEND IT
TO_ADDRESS = ''

#BTC MINER FEE TO PAY - TRANSACTION COST, IF TOO LOW CAN CAUSE AN ERROR
FEE = 0.00010000

#PRIVATE KEY ARRAY USED TO CREATE MULTISIG ADDRESS
PK1 = '["PK1"]'
PK2 = '["PK2"]'
PK3 = '["PK3"]'
PK4 = '["PK4"]'
PK5 = '["PK5"]'

#REDEEM_SCRIPT DOES NOT CHANGE FOR MULTISIG ADDRESS
REDEEM_SCRIPT = ''
